Close mobile menu on link click
grundeinkommensbuero/next-prototype pull request #16
Opened 2022-06-21 15:25 UTC by nmauersberg

This pr adds the functionality to close the mobile menu overlay, when an action is clicked.

Also mobile and desktop menu components are now in separate folders to make it a bit more clear, which are which.

A small enhancement of the dynamic actions sneaked into this PR, it was not intentional, but the commit must have went in. Maybe you could have a look on that too @Valioesi ? I left a comment where it was in the code.

2022-06-23 16:17 UTC, schaerta requested changes
It looks great, there's just one little bug: When the menu gets too long on mobile (after having logged in), I can't scroll down. Because of that I can't reach the logout option.

2022-06-27 10:37 UTC, nmauersberg commented
Thx for spotting this! It should be fixed now!

2022-06-27 10:40 UTC, nmauersberg commented on components/Section/index.tsx
> +  // Some actions might be imported from the _actions.ts file,
Here is the change explained, regarding the dynamic action. @Valioesi

2022-06-28 11:07 UTC, Valioesi commented on components/Section/index.tsx
> +  // Some actions might be imported from the _actions.ts file,
Makes sense

2022-06-28 11:13 UTC, schaerta approved these changes
Thanks :)

2022-06-28 11:17 UTC, Valioesi requested changes
The layout in the dropdowns seem kinda off (text not placed under the parent item). 
Other than that and the question I had, looks good!

2022-06-28 11:17 UTC, Valioesi commented on layout/Header/MainMenu/MenuLink.tsx
> +          if (extraCallback) extraCallback();
Does this work in an a tag?

2022-06-28 11:25 UTC, Valioesi commented on layout/Header/style.module.scss
> +  min-height: $headerHeight;
Why not just height? If min-height and max-height is the same, it's kinda redundant, or am I missing something?

2022-06-28 14:39 UTC, nmauersberg commented on layout/Header/MainMenu/MenuLink.tsx
> +          if (extraCallback) extraCallback();
Yes :) Fount this pattern on the internet, somewhere...

2022-06-28 17:15 UTC, nmauersberg commented
> The layout in the dropdowns seem kinda off (text not placed under the parent item). Other than that and the question I had, looks good!

@Valioesi  What do you mean? For me it looks exactly as on the original page. I think the placement was on purpose.

2022-06-29 09:17 UTC, nmauersberg commented
Ah, I thought you'd mean the content of the mobile menu.
Gotcha!

2022-06-29 18:18 UTC, merged