Collectors signup
grundeinkommensbuero/next-prototype pull request #21
Opened 2022-07-01 14:18 UTC by Valioesi

I transferred the 3 pages of the sign up flow for collectors. Also fixed the image upload (new chosen image was not shown and arrow not rendered) and external links (not opening due to href not being set). 

To test: goto /sammeln/anmelden and walk through the flow.

2022-07-04 16:05 UTC, nmauersberg requested changes
Testing it I entered 110 as my phone number and it failed only after submitting, but without an error message. I landed on the default error screen: "Ops, bei uns ist etwas schief gegangen".

The rest went fine. The new disabled fields are a nice improvement!

2022-07-04 16:05 UTC, nmauersberg commented on components/Forms/SignUp/index.tsx
> +  if (values.phoneNumber && !validatePhoneNumber(values.phoneNumber)) {
This was somehow not triggered, when entering 110

2022-07-06 09:09 UTC, Valioesi commented on pages/sammeln/anmelden/index.tsx
> +            fieldsToRender={[
Nice, thanks! Yeah, I added that already in the old project. Pretty useful, cause this way I could also easily implement the SmallSignup with only the email field

2022-07-08 12:50 UTC, Valioesi commented on components/Forms/SignUp/index.tsx
> +  if (values.phoneNumber && !validatePhoneNumber(values.phoneNumber)) {
Oh yeah, apparently I added a stricter phone validation (at least 6 digits) on the backend side. Maybe I forgot to add it in the frontend back then. So this bug was there in the old project as well. But probably not a huge deal so far.

2022-07-11 09:54 UTC, nmauersberg commented
@Valioesi Cool, now it works for me.

But on the profile page the Image is too large. Is it the same for you?

![Profile-Image](https://user-images.githubusercontent.com/74594947/178238758-5a0486ba-c82d-4513-ae25-fe474d86ca1b.png)

2022-07-11 09:55 UTC, nmauersberg approved these changes
The rest was fine for me. :)

2022-07-12 08:17 UTC, merged