Grid element vertically centered
grundeinkommensbuero/next-prototype pull request #51
Opened 2022-08-05 13:21 UTC by Valioesi

I added align-self to grid elements and made the margin smaller. Margins + padding should now be the same as in Gatsby. 
I don't see any red flags the vertical alignment tbh. Looks good everywhere I checked.

2022-08-05 13:43 UTC, schaerta requested changes
<img width="678" alt="image" src="https://user-images.githubusercontent.com/17318585/183089705-f22b020a-e1b4-4d60-bef9-148dccd23f8e.png">
Hmm, now there are gaps on the big screen. I'm not convinced. ^^"

2022-08-05 14:18 UTC, Valioesi commented
I am not sure I get it. What's different to before? @schaerta

2022-08-08 07:14 UTC, schaerta commented
> I am not sure I get it. What's different to before? @schaerta

Sorry, I think I was seeing things! You're right, it looks fine!

2022-08-08 07:14 UTC, schaerta approved these changes

2022-08-10 09:49 UTC, merged